version: 0.2
env:
  variables:
    RAILS_ENV: "development"
phases:
  install:
    runtime-versions:
        docker: 18
    commands:
      - echo "hello"
      - curl -L "https://github.com/docker/compose/releases/download/1.25.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
  pre_build:
    commands:
    - echo Logging in to Amazon ECR....
  build:
    commands:
    - echo Build started on `date`
    - echo $PATH
      #    - curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
    - /usr/local/bin/docker-compose up -d
    - /usr/local/bin/docker-compose exec -T  web '/mnt/rake_test.sh' 
      #    - aws s3 cp /tmp/rails-app.zip s3://test-rails-cc-lokesh/ 
      #    - docker run  -e REDIS_URL='redis://test-redis.pjfegb.ng.0001.use1.cache.amazonaws.com:6379/1' -e RACK_ENV=development --name rubyapp -v `pwd`:/mnt lokeshjawane/ubuntu-ruby:2.1.0 /bin/bash /mnt/script.sh
  post_build:
    commands:
    - echo Build completed on `date`
