version: 0.2
env:
  variables:
    RAILS_ENV: "development"
phases:
  install:
    runtime-versions:
        docker: 18
    commands:
      - echo "hello"
  pre_build:
    commands:
    - echo Logging in to Amazon ECR....
    - echo "installing aws-sdk-ecr"
    - gem install 'aws-sdk-ecr'
    - echo "Creating folders for pid files"
    - mkdir shared
    - mkdir shared/pids
    - mkdir shared/sockets
  build:
    commands:
    - echo Build started on `date`
    - echo $PATH
    - gem install bundler -v  '1.17.3'
    - bundle install
    - bundle exec rake db:migrate
      #    - docker run  -e REDIS_URL='redis://test-redis.pjfegb.ng.0001.use1.cache.amazonaws.com:6379/1' -e RACK_ENV=development --name rubyapp -v `pwd`:/mnt lokeshjawane/ubuntu-ruby:2.1.0 /bin/bash /mnt/script.sh
  post_build:
    commands:
    - echo Build completed on `date`
