steps:
- id: git-submodule
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  env: ['GIT_DISCOVERY_ACROSS_FILESYSTEM=1']
  args:
  - '-c'
  - |
    git init
    git config -f .gitmodules submodule.blog.url https://github.com/lokeshjawane/blog.git
    git submodule init
    git submodule update
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/rsaf-puvss/testing', '.']

