version: 2.1
jobs:
  build:
    docker: 
      - image: ruby:2.5 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: bundle install # run the `echo` command

