version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1-node
        environment:
          DATABASE_HOST: localhost
          DATABASE_USER: ubuntu
          DATABASE_PASSWORD: ubuntu
          DATABASE_DBNAME: app_test
          RAILS_ENV: test
          RACK_ENV: test
          DEFAULT_HOST: codefund.io
          PARALLEL_WORKERS: "1"
          REDIS_CACHE_URL: redis://127.0.0.1:6379
          REDIS_QUEUE_URL: redis://127.0.0.1:6379
          WORDPRESS_URL: 'https://codefund.io'
      - image: circleci/postgres:11.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: app_test
    steps:
      - checkout
      - run:
         name: Install gem dependencies
         command: |
           gem install bundler:1.17.2
           bundle check || bundle install --jobs=6 --retry=3 --path vendor/bundle

workflows:
  version: 2
  build-deploy:
    jobs:
    - build
