version: 2.1

jobs:
 test:
  working_directory: ~/repo
  docker:
    # The first image is the primary image. This is where the commands below
    # will run within.
    - image: circleci/ruby:2.6.5-node-browsers
      environment:
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        DATABASE_URL: "postgresql://root@localhost/my_project_test?pool=5"
    # For more information about how these images work, check our their READMEs
    # https://hub.docker.com/r/circleci/ruby/
    # https://hub.docker.com/r/circleci/postgres/
    # https://hub.docker.com/_/postgres/
    - image: circleci/postgres:9.3-alpine-ram
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: my_project_test
  steps:
      - checkout
      - run:
         name: Install gem dependencies
         command: |
           gem install bundler:1.17.2
           bundle check || bundle install --jobs=6 --retry=3 --path vendor/bundle

workflows:
  version: 2
  build-deploy:
    jobs:
    - build
